#!/usr/bin/env python3

import os

import testbox


test_command = ['SOKOBAN.EXE']

configuration = {
    'sdl': {'autolock': 'false'},
    'cpu': {'cycles': 'max'},
    'render': {'scaler': 'normal5x'},
    'mixer': {'nosound': 'true'},
    'midi': {'mididevice': 'none'},
    'sblaster': {'sbtype': 'none'},
    'speaker': {'pcspeaker': 'false'},
}

environment = os.environ.copy()
environment['SDL_AUDIODRIVER'] = ''

with testbox.TestBox(configuration, test_command, environment) as box:
    box.wait_image('images/graphics.png', timeout=1)
    box.send_keys('C\r') # CGA mode.

    box.wait_image('images/input.png', timeout=1)
    box.send_keys('K\r') # Input from keyboard.

    box.wait_image('images/door.png', timeout=5)
    box.send_keys('\r') # Enter door.

    box.wait_image('images/lobby.png', timeout=1)
    box.send_keys('\r') # Enter elevator.

    box.wait_image('images/menu.png', timeout=5)
    box.send_keys('TEST\r') # Enter player name.

    box.wait_image('images/start.png', timeout=1)
    box.send_keys('\r') # Select single player mode.

    box.wait_image('images/elevator.png', timeout=1)
    box.send_keys('1A') # Select first floor and accept.

    # TODO make auto solver
    # TODO probably there is more optimal route
    for step, keys in (
        ('one', '▴◂◂◂▴▴▴◂▴◂◂▾◂◂▾▾▾▸▸▸▸▸▸▸▸▸▸▸▸▸▾▸▴◂◂'),
        ('two', '◂◂◂◂◂◂◂▴▴▴◂▴◂◂▾▾▾▴▴◂◂▾▾▾▸▸▸▸▸▸▸▸▸▸▸▸▴▸▾◂▾▸▴◂'),
        ('three', '◂◂◂◂◂◂◂▴▴▴◂◂▴◂▾▾▾▴▴◂◂▾▾▾▸▸▸▸▸▸▸▸▸▸▸▸▾▸▴◂'),
        ('four', '◂◂◂◂◂◂◂▴▴▴◂◂▴▴▴◂▾▾▾▾▾▴▴◂◂▾▾▾▸▸▸▸▸▸▸▸▸▸▸▴▸▾◂▾▸▴'),
        ('five', '◂◂◂◂◂◂◂▴▴▴◂◂▴▴▴▸▾▾◂◂▾◂◂▾▾◂◂▾▸▸▸▸▸▸▸▸▸▸▸▸▸▸▸◂'),
        ('six', '◂◂◂◂◂◂◂▴▴▴◂◂▴◂▾▾▾▴▴◂◂▾▾▾▸▸▸▸▸▸▸▸▸▸▸▸'),
    ):
        # Checkpoint, skipping status bar.
        image = box.wait_image(f'images/step-{step}.png', (0, 0, 320, 191), timeout=2)

        for key in keys:
            box.send_keys(key)
            # Waiting move counter to update.
            image = box.wait_change(image, (75, 191, 110, 200), timeout=1)

    box.wait_image('images/win.png', timeout=10) # Level 2.
