version: "3"

services:
  testbox:
    build: .
    image: testbox
    pull_policy: build

  test:
    build:
      dockerfile: example/Dockerfile
    environment:
    - DISPLAY
    volumes:
    - "/tmp/.X11-unix:/tmp/.X11-unix"
    - "/dev/snd:/dev/snd"
    depends_on:
    - testbox
