#!/usr/bin/env python3

import os
import shutil
import subprocess


for i in os.listdir('example/application'):
    path = os.path.join('example/application', i)
    shutil.move(path, '/tmp/movedfile')
    try:
        subprocess.run('docker-compose -f docker-compose.example.yml run test', shell=True, stderr=subprocess.DEVNULL, stdout=subprocess.DEVNULL, check=True)
        print(i, 'is not needed')
    except Exception:
        print(i, 'is needed')
    shutil.move('/tmp/movedfile', path)
